import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

async function read(path) {
  return readFile(new URL(path, import.meta.url), 'utf8')
}

test('app renders sidebar account switcher component', async () => {
  const app = await read('../src/App.vue')
  const component = await read('../src/components/sidebar/SidebarAccountSwitcher.vue')
  const router = await read('../src/router/index.ts')

  assert.match(component, /account-switcher/)
  assert.match(component, /defineProps/)
  assert.match(component, /暂无账号档案/)
  assert.match(component, /当前 Web 运行时/)
  assert.match(component, /formatProfileLabel\(/)
  assert.match(component, /emit\('switch'/)
  assert.match(component, /emit\('align'/)
  assert.match(component, /emit\('remove'/)
  assert.match(component, /onAddByEmailLogin\(/)
  assert.match(component, /邮箱登录新增档案/)
  assert.doesNotMatch(component, /对齐账号/)
  assert.match(component, /管理账号/)
  assert.match(component, /account-switcher-manage-list/)
  assert.doesNotMatch(component, /account-switcher-sheet/)
  assert.doesNotMatch(component, /openMobileSheet\(/)
  assert.doesNotMatch(component, /closeMobileSheet\(/)
  assert.doesNotMatch(component, /Teleport/)
  assert.match(component, /onSwitch\(/)
  assert.match(component, /onRemove\(/)
  assert.match(component, /visibleProfiles/)
  assert.match(component, /isCurrentAccountProfile\(/)
  assert.match(component, /accountRateLimitUsageByProfileId/)
  assert.match(component, /resolveQuotaRemainingLabel\(/)
  assert.match(component, /周剩余/)
  assert.match(component, /5小时剩余/)
  assert.doesNotMatch(component, /切换活跃账号/)
  assert.doesNotMatch(component, /sidebar-account-switcher-select/)
  assert.doesNotMatch(component, /function onSelect\(event: Event\)/)
  assert.match(component, /切换到该账号/)
  assert.match(component, /切换/)
  assert.doesNotMatch(component, /Access Token/)
  assert.match(component, /profile\.profileId === props\.activeAccountProfileId/)
  assert.match(component, /if \(!normalizedProfileId \|\| normalizedProfileId === props\.activeAccountProfileId\) return/)
  assert.match(component, /当前档案不可删除/)
  assert.match(app, /SidebarAccountSwitcher/)
  assert.match(app, /onOpenAccountCenter\(/)
  assert.match(app, /账号中心/)
  assert.match(app, /IconTablerSettings/)
  assert.match(app, /@click=\"onOpenAccountCenter\"/)
  assert.match(app, /route\.name === 'accountCenter'/)
  assert.match(app, /router\.push\(\{ name:\s*'accountCenter' \}\)/)
  assert.match(app, /:account-profiles=\"accountProfiles\"/)
  assert.match(app, /:active-account-profile-id=\"activeAccountProfileId\"/)
  assert.match(app, /:account-rate-limit-usage-by-profile-id=\"accountRateLimitUsageByProfileId\"/)
  assert.match(app, /@switch=\"onSwitchAccountProfile\"/)
  assert.match(app, /@align=\"onAlignAccount\"/)
  assert.match(app, /@remove=\"onRemoveAccountProfile\"/)
  assert.match(app, /class=\"account-center-switcher\"/)
  assert.doesNotMatch(app, /class=\"sidebar-account-switcher-host\"/)
  assert.doesNotMatch(app, /function onAddAccountProfile\(/)
  assert.match(app, /function onRemoveAccountProfile\(/)
  assert.match(app, /function scheduleAccountAlignmentRefresh\(\): void/)
  assert.match(app, /window\.setInterval\(/)
  assert.match(app, /scheduleAccountAlignmentRefresh\(\)/)
  assert.match(router, /path:\s*'\/account-center'/)
  assert.match(router, /name:\s*'accountCenter'/)
})
